# Generated by Django 4.1.7 on 2023-04-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del alumno')),
                ('apellidoP', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellidoM', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.especialidad')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
