# Generated by Django 4.1.7 on 2023-04-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={},
        ),
    ]
