# Generated by Django 4.1.7 on 2023-04-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_alter_alumno_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='numControl',
            field=models.CharField(default=332323244232332, max_length=50, unique=True, verbose_name='Numero de control'),
            preserve_default=False,
        ),
    ]
